### ISSUE TITLE
Feature Request: storage tracker should show total number of VIP.

### ISSUE THREAD

**Issue by moritz** [taustation-fan/userscripts#26]
It would be very convenient if the storage tracker showed the total number of VIP that is available in storage and VIP (so for example if you 5x 3-day VIP packs in storage and one 1-day VIP in inventory, it should show 16 days).

I know this wasn't the original intent of the storage tracker, but it already has all the data, and that could tell me how many credits to invest into buying VIP on the market.

**Comment by moritz** [comment]
@tauhead I'd like to get your opinion on this issue (bonus points if you implement it :D).

**Comment by dot-sent** [comment]
I'd suggest to add the counters for rations as well - very useful if you have rations of different tiers scattered across many different stations.

**Comment by moritz** [comment]
This has been (mostly) implemented in #30
